version: '3.8'

services:
  mab-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mab_db
      MYSQL_USER: mab_user
      MYSQL_PASSWORD: mab_password
    ports:
      - "3306:3306"
    volumes:
      - mab_db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s
    networks:
      - mab-network
    restart: unless-stopped

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mab-db
    depends_on:
      - mab-db
    networks:
      - mab-network
    restart: unless-stopped

volumes:
  mab_db_data:

networks:
  mab-network:
    driver: bridge
