version: '3.8'

services:
  mab-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - GRAILS_DATASOURCE_URL=jdbc:mysql://mab-db:3306/mab_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - GRAILS_DATASOURCE_USERNAME=mab_user
      - GRAILS_DATASOURCE_PASSWORD=mab_password
      - GRAILS_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - GRAILS_DATASOURCE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    depends_on:
      mab-db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - mab-network

  mab-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mab_db
      MYSQL_USER: mab_user
      MYSQL_PASSWORD: mab_password
    ports:
      - "3306:3306"
    volumes:
      - mab_db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 30s
      start_period: 60s
    restart: unless-stopped
    networks:
      - mab-network

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mab-db
    depends_on:
      - mab-db
    restart: unless-stopped
    networks:
      - mab-network

volumes:
  mab_db_data:

networks:
  mab-network:
    driver: bridge